name: DbStats
version: 0.4.1
slug: dbstats
description: Database stats for Home Assistant
image: ghcr.io/jehy/hass-dbstats-addon
url: https://github.com/jehy/hass-addons/blob/master/dbstats/README.MD
codenotary: fate@jehy.ru
ingress: true
ingress_port: 6060
ingress_stream: true
panel_icon: mdi:database
init: false
homeassistant: 2022.1.1
hassio_api: true
options:
  connectionString: ""
schema:
  connectionString: str
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  80/tcp: 6060
ports_description:
  80/tcp: Web interface
map:
  - homeassistant_config:ro
