system_database:
  recorder:
    purge_keep_days: 30
    db_url: !secret db_url
    exclude:
      entity_globs:
        - sensor.sun*
        - weather.*
      entities:
        - sensor.last_boot # Comes from 'systemmonitor' sensor platform
        - sun.sun # Don't record sun data
