group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include_dir_merge_list template
binary_sensor: !include_dir_merge_list sensors_binary
sensor: !include_dir_merge_list sensors


recorder:
  purge_keep_days: 30
  db_url: !secret db_url
  exclude:
    entity_globs:
      - sensor.sun*
      - weather.*
    entities:
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sun.sun # Don't record sun data

# - platform: sql
sql:
  - name: psql_size
    #scan_interval: 10
    unique_id: psql_size
    query: "SELECT (pg_database_size('homeass')/1024/1024) as db_size;"
    column: "db_size"
    unit_of_measurement: MB
