name: PublishAddon

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: 'jehy/hass-dbstats-addon'

on:
  release:
    types: [published]
jobs:
  release_db_stats_addon:
    name: ReleaseDbStatsAddon
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}
            type=raw,value=stable
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --armv7 \
            --amd64 \
            --aarch64 \
            --target dbstats \
            --docker-hub hass-dbstats \
            --release-tag ${{ env.IMAGE_NAME}} \
            --additional-tag stable

#      - name: Build and push Docker image
#        uses: docker/build-push-action@v5
#        with:
#          context: ./dbstats
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
