name: Publish

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  release:
    types: [published]
jobs:
  release_db_stats_docker:
    name: ReleaseDbStats
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}
            type=raw,value=dev
      - name: Use Node.js 20.11.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
      - name: 'change backend version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: env.RELEASE_VERSION
          package: './backend'
          git-tag-version: 'false'
      - name: 'change frontend  version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: env.RELEASE_VERSION
          package: './frontend'
          git-tag-version: 'false'
      - name: Install shared deps
        working-directory: ./shared
        run: npm ci
      - name: Install backend deps
        working-directory: ./backend
        run: npm ci
      - name: build back
        working-directory: ./backend
        run: npm run build
      - name: clean back
        working-directory: ./backend
        run: npm  ci --omit=dev
      - name: Install frontend deps
        working-directory: ./frontend
        run: npm ci
      - name: build front
        working-directory: ./frontend
        run: npm run build
      - name: copy front to back
        run: cp frontend/build backend/dist/ -r
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
